# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "debug"
appidBinding: "binding-workshop-team-one-appid"
image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: false

ingress:
  enabled: true
  appid:
    enabled: false
    requestType: web


  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: inventory

connectsTo: inventory-management-bff-solution

runtime: js
